### ISSUE TITLE
> @Martinus123S kayak yang dibilangin bang @polan1133 untuk ngurangin kompleksitas bisa juga loop untuk cari pembaginya cuman sampe akar dari N aja

### ISSUE THREAD

**Issue by friskals** [ITDel-Programming/TLX-PD#11]
> @Martinus123S kayak yang dibilangin bang @polan1133 untuk ngurangin kompleksitas bisa juga loop untuk cari pembaginya cuman sampe akar dari N aja

aku tadi maunya biar di temukan sendiri rumusnya @FriskaLSianturi dengan bantuan hint dari kita wkwkwk... tapi gpp mungkin juga dia agak susah kepikiran kesana

_Originally posted by @polan1133 in https://github.com/ITDel-Programming/TLX-PD/pull/10#issuecomment-623078293_

**Comment by davidtompul** [comment]
btw ini isu apa ya?

**Comment by polan1133** [comment]
> btw ini isu apa ya?

hoo.. ini si @FriskaLSianturi coba2 fitur wkwk
